### ISSUE TITLE
Cuckoo API not running

### ISSUE THREAD

**Issue by Zabeh-Hakimi** [mohamedbenchikh/MDML#2]
Hello, I hope you are fine.
This works fine on PE (.exe) files that I upload but when I upload the other file extensions such as docx,pdf etc.. It says that Cuckoo Api is not running. Do you know how to solve this problem?

Best regards.

**Comment by Zabeh-Hakimi** [comment]
BTW, while installation of ssdeep on python3.7 (and 3.10 also) I get this error do you know how to solve this?

Collecting ssdeep
  Using cached ssdeep-3.4.tar.gz (110 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [105 lines of output]
      running egg_info
      creating C:\Users\Mutex\AppData\Local\Temp\pip-pip-egg-info-i49bprf9\ssdeep.egg-info
      writing C:\Users\Mutex\AppData\Local\Temp\pip-pip-egg-info-i49bprf9\ssdeep.egg-info\PKG-INFO
      writing dependency_links to C:\Users\Mutex\AppData\Local\Temp\pip-pip-egg-info-i49bprf9\ssdeep.egg-info\dependency_links.txt
      writing requirements to C:\Users\Mutex\AppData\Local\Temp\pip-pip-egg-info-i49bprf9\ssdeep.egg-info\requires.txt
      writing top-level names to C:\Users\Mutex\AppData\Local\Temp\pip-pip-egg-info-i49bprf9\ssdeep.egg-info\top_level.txt
      writing manifest file 'C:\Users\Mutex\AppData\Local\Temp\pip-pip-egg-info-i49bprf9\ssdeep.egg-info\SOURCES.txt'
      _ssdeep_cffi_a28e5628x27adcb8d.c
      src\ssdeep\__pycache__\_ssdeep_cffi_a28e5628x27adcb8d.c(266): fatal error C1083: Cannot open include file: 'fuzzy.h': No such file or directory
      C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\pep425tags.py:89: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
        warn=(impl == 'cp')):
      C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\pep425tags.py:93: RuntimeWarning: Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
        warn=(impl == 'cp')):
      Traceback (most recent call last):
        File "C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\distutils\_msvccompiler.py", line 423, in compile
          self.spawn(args)
        File "C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\distutils\_msvccompiler.py", line 542, in spawn
          return super().spawn(cmd)
        File "C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\distutils\ccompiler.py", line 909, in spawn
          spawn(cmd, dry_run=self.dry_run)
        File "C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\distutils\spawn.py", line 38, in spawn
          _spawn_nt(cmd, search_path, dry_run=dry_run)
        File "C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\distutils\spawn.py", line 81, in _spawn_nt
          "command %r failed with exit status %d" % (cmd, rc))
      distutils.errors.DistutilsExecError: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "c:\users\mutex\appdata\local\temp\pip-install-o0_cdxmp\ssdeep_c6c40d0a41ce4abc8fdafd4d0e59b41c\.eggs\cffi-1.15.1-py3.7-win-amd64.egg\cffi\ffiplatform.py", line 51, in _build
          dist.run_command('build_ext')
        File "C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\build_ext.py", line 78, in run
          _build_ext.run(self)
        File "C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\distutils\command\build_ext.py", line 339, in run
          self.build_extensions()
        File "C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\distutils\command\build_ext.py", line 448, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\build_ext.py", line 199, in build_extension
          _build_ext.build_extension(self, ext)
        File "C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\distutils\command\build_ext.py", line 533, in build_extension
          depends=ext.depends)
        File "C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\distutils\_msvccompiler.py", line 425, in compile
          raise CompileError(msg)
      distutils.errors.CompileError: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Mutex\AppData\Local\Temp\pip-install-o0_cdxmp\ssdeep_c6c40d0a41ce4abc8fdafd4d0e59b41c\setup.py", line 165, in <module>
          ext_package="ssdeep",
        File "C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\__init__.py", line 129, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\egg_info.py", line 278, in run
          self.find_sources()
        File "C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\egg_info.py", line 293, in find_sources
          mm.run()
        File "C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\egg_info.py", line 524, in run
          self.add_defaults()
        File "C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\egg_info.py", line 560, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\distutils\command\sdist.py", line 226, in add_defaults
          self._add_defaults_python()
        File "C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\sdist.py", line 127, in _add_defaults_python
          build_py = self.get_finalized_command('build_py')
        File "C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 299, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 107, in ensure_finalized
          self.finalize_options()
        File "C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\build_py.py", line 34, in finalize_options
          orig.build_py.finalize_options(self)
        File "C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\distutils\command\build_py.py", line 45, in finalize_options
          ('force', 'force'))
        File "C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 287, in set_undefined_options
          src_cmd_obj.ensure_finalized()
        File "C:\Users\Mutex\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 107, in ensure_finalized
          self.finalize_options()
        File "C:\Users\Mutex\AppData\Local\Temp\pip-install-o0_cdxmp\ssdeep_c6c40d0a41ce4abc8fdafd4d0e59b41c\setup.py", line 24, in finalize_options
          self.distribution.ext_modules = get_ext_modules()
        File "C:\Users\Mutex\AppData\Local\Temp\pip-install-o0_cdxmp\ssdeep_c6c40d0a41ce4abc8fdafd4d0e59b41c\setup.py", line 79, in get_ext_modules
          binding.verify()
        File "C:\Users\Mutex\AppData\Local\Temp\pip-install-o0_cdxmp\ssdeep_c6c40d0a41ce4abc8fdafd4d0e59b41c\src\ssdeep\binding.py", line 132, in verify
          libraries=self._libraries,
        File "c:\users\mutex\appdata\local\temp\pip-install-o0_cdxmp\ssdeep_c6c40d0a41ce4abc8fdafd4d0e59b41c\.eggs\cffi-1.15.1-py3.7-win-amd64.egg\cffi\api.py", line 468, in verify
          lib = self.verifier.load_library()
        File "c:\users\mutex\appdata\local\temp\pip-install-o0_cdxmp\ssdeep_c6c40d0a41ce4abc8fdafd4d0e59b41c\.eggs\cffi-1.15.1-py3.7-win-amd64.egg\cffi\verifier.py", line 105, in load_library
          self._compile_module()
        File "c:\users\mutex\appdata\local\temp\pip-install-o0_cdxmp\ssdeep_c6c40d0a41ce4abc8fdafd4d0e59b41c\.eggs\cffi-1.15.1-py3.7-win-amd64.egg\cffi\verifier.py", line 202, in _compile_module
          outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
        File "c:\users\mutex\appdata\local\temp\pip-install-o0_cdxmp\ssdeep_c6c40d0a41ce4abc8fdafd4d0e59b41c\.eggs\cffi-1.15.1-py3.7-win-amd64.egg\cffi\ffiplatform.py", line 22, in compile
          outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
        File "c:\users\mutex\appdata\local\temp\pip-install-o0_cdxmp\ssdeep_c6c40d0a41ce4abc8fdafd4d0e59b41c\.eggs\cffi-1.15.1-py3.7-win-amd64.egg\cffi\ffiplatform.py", line 58, in _build
          raise VerificationError('%s: %s' % (e.__class__.__name__, e))
      cffi.VerificationError: CompileError: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

thanks

**Comment by mohamedbenchikh** [comment]
Hi,

Please make sure [Cuckoo sandbox](https://0x0c.cc/2020/03/19/Install-a-Cuckoo-Sandbox-in-12-steps/) is installed on local/remote machine (you can install it on a VM), then update config.yaml with its corresponding address.
